version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bitlab-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bitlab_db
      POSTGRES_MULTIPLE_DATABASES: keycloak
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bitlab-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: bitlab-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    command:
      - start-dev
    ports:
      - "8180:8080"
    depends_on:
      - postgres
    networks:
      - bitlab-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # веб-интерфейс и API
      - "9001:9001"   # админ-панель
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - bitlab-network

  createbucket:
    image: minio/mc
    container_name: createbucket
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        echo '⏳ Ожидаем MinIO...';
        until curl -s http://minio:9000/minio/health/live; do
          sleep 1;
        done;
        echo '✅ MinIO готов, создаём bucket...';
        mc alias set myminio http://minio:9000 minioadmin minioadmin --insecure &&
        mc mb myminio/mybucket &&
        mc anonymous set upload myminio/mybucket &&
        mc anonymous set download myminio/mybucket;
        echo '🏁 Всё готово.';
      "
    networks:
      - bitlab-network

volumes:
  postgres-data:
  minio-data:

networks:
  bitlab-network:
    driver: bridge