version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bitlab-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bitlab_db
      POSTGRES_MULTIPLE_DATABASES: keycloak
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bitlab-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: bitlab-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    command:
      - start-dev
    ports:
      - "8180:8080"
    depends_on:
      - postgres
    networks:
      - bitlab-network

volumes:
  postgres-data:

networks:
  bitlab-network:
    driver: bridge