keycloak:
  credentials:
    secret: j5uTH7DnfVXKrjyv2tWFOyhWSh3UYktc

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/bitlab
          jwk-set-uri: http://localhost:8180/realms/bitlab/protocol/openid-connect/certs